// Package xo contains the types for schema 'aypcddg'.
package xo

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"j7go/components"
	"j7go/utils"

	"go.uber.org/zap"
)

// Adv2Page represents a row from 'aypcddg.adv2_pages'.
type Adv2Page struct {
	ID         int            `json:"id"`          // id
	Fid        sql.NullInt64  `json:"fid"`         // fid
	PageName   sql.NullString `json:"page_name"`   // page_name
	PageNo     sql.NullString `json:"page_no"`     // page_no
	OpenStatus sql.NullInt64  `json:"open_status"` // open_status
	Status     sql.NullInt64  `json:"status"`      // status
	Created    sql.NullInt64  `json:"created"`     // created
	Updated    sql.NullInt64  `json:"updated"`     // updated
	Channel    sql.NullInt64  `json:"channel"`     // channel

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Adv2Page exists in the database.
func (a *Adv2Page) Exists() bool { //adv2_pages
	return a._exists
}

// Deleted provides information if the Adv2Page has been deleted from the database.
func (a *Adv2Page) Deleted() bool {
	return a._deleted
}

// Get table name
func GetAdv2PageTableName(key ...interface{}) (string, error) {
	tableName, err := components.M.GetTable(components.E.Opts.DBConfig.Name, "adv2_pages", key...)
	if err != nil {
		return "", err
	}
	return tableName, nil
}

// Insert inserts the Adv2Page to the database.
func (a *Adv2Page) Insert(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB
	var res sql.Result
	// if already exist, bail
	if a._exists {
		return errors.New("insert failed: already exists")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetAdv2PageTableName(key...)
	if err != nil {
		return err
	}

	// sql insert query, primary key provided by autoincrement
	sqlstr := `INSERT INTO ` + tableName +
		` (` +
		`fid, page_name, page_no, open_status, status, created, updated, channel` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel)))
	if err != nil {
		return err
	}
	if tx != nil {
		res, err = tx.Exec(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel)
	} else {
		res, err = dbConn.Exec(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel)
	}

	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	a.ID = int(id)
	a._exists = true

	return nil
}

// Update updates the Adv2Page in the database.
func (a *Adv2Page) Update(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if a._deleted {
		return errors.New("update failed: marked for deletion")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetAdv2PageTableName(key...)
	if err != nil {
		return err
	}

	// sql query
	sqlstr := `UPDATE ` + tableName + ` SET ` +
		`fid = ?, page_name = ?, page_no = ?, open_status = ?, status = ?, created = ?, updated = ?, channel = ?` +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel, a.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel, a.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, a.Fid, a.PageName, a.PageNo, a.OpenStatus, a.Status, a.Created, a.Updated, a.Channel, a.ID)
	}
	return err
}

// Save saves the Adv2Page to the database.
func (a *Adv2Page) Save(ctx context.Context) error {
	if a.Exists() {
		return a.Update(ctx)
	}

	return a.Insert(ctx)
}

// Delete deletes the Adv2Page from the database.
func (a *Adv2Page) Delete(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if a._deleted {
		return nil
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetAdv2PageTableName(key...)
	if err != nil {
		return err
	}
	//1

	// sql query with composite primary key
	sqlstr := `UPDATE ` + tableName + ` SET is_del = 1 WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, a.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, a.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, a.ID)
	}

	if err != nil {
		return err
	}

	// set deleted
	a._deleted = true

	return nil
}

// Adv2PageByID retrieves a row from 'aypcddg.adv2_pages' as a Adv2Page.
//
// Generated from index 'adv2_pages_id_pkey'.
func Adv2PageByID(ctx context.Context, id int, key ...interface{}) (*Adv2Page, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetAdv2PageTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, page_name, page_no, open_status, status, created, updated, channel ` +
		`FROM ` + tableName +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, id)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	a := Adv2Page{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, id).Scan(&a.ID, &a.Fid, &a.PageName, &a.PageNo, &a.OpenStatus, &a.Status, &a.Created, &a.Updated, &a.Channel)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, id).Scan(&a.ID, &a.Fid, &a.PageName, &a.PageNo, &a.OpenStatus, &a.Status, &a.Created, &a.Updated, &a.Channel)
		if err != nil {
			return nil, err
		}
	}

	return &a, nil
}

// Adv2PagesByStatus retrieves a row from 'aypcddg.adv2_pages' as a Adv2Page.
//
// Generated from index 'status'.
func Adv2PagesByStatus(ctx context.Context, status sql.NullInt64, key ...interface{}) ([]*Adv2Page, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetAdv2PageTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, page_name, page_no, open_status, status, created, updated, channel ` +
		`FROM ` + tableName +
		` WHERE status = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, status)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	var queryData *sql.Rows
	if tx != nil {
		queryData, err = tx.Query(sqlstr, status)
		if err != nil {
			return nil, err
		}
	} else {
		queryData, err = dbConn.Query(sqlstr, status)
		if err != nil {
			return nil, err
		}
	}

	defer queryData.Close()

	// load results
	res := make([]*Adv2Page, 0)
	for queryData.Next() {
		a := Adv2Page{
			_exists: true,
		}

		// scan
		err = queryData.Scan(&a.ID, &a.Fid, &a.PageName, &a.PageNo, &a.OpenStatus, &a.Status, &a.Created, &a.Updated, &a.Channel)
		if err != nil {
			return nil, err
		}

		res = append(res, &a)
	}

	return res, nil
}
