// Package xo contains the types for schema 'aypcddg'.
package xo

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"j7go/components"
	"j7go/utils"

	"github.com/go-sql-driver/mysql"
	"go.uber.org/zap"
)

// FactoryConfigCommission represents a row from 'aypcddg.factory_config_commission'.
type FactoryConfigCommission struct {
	ID           uint64         `json:"id"`             // id
	Fid          int            `json:"fid"`            // fid
	Gcid         int            `json:"gcid"`           // gcid
	Gid          int            `json:"gid"`            // gid
	PlusPercent  float64        `json:"plus_percent"`   // plus_percent
	AbsPlusPrice float64        `json:"abs_plus_price"` // abs_plus_price
	CreatedAt    mysql.NullTime `json:"created_at"`     // created_at
	UpdatedAt    mysql.NullTime `json:"updated_at"`     // updated_at
	BrandID      int            `json:"brand_id"`       // brand_id

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the FactoryConfigCommission exists in the database.
func (fcc *FactoryConfigCommission) Exists() bool { //factory_config_commission
	return fcc._exists
}

// Deleted provides information if the FactoryConfigCommission has been deleted from the database.
func (fcc *FactoryConfigCommission) Deleted() bool {
	return fcc._deleted
}

// Get table name
func GetFactoryConfigCommissionTableName(key ...interface{}) (string, error) {
	tableName, err := components.M.GetTable(components.E.Opts.DBConfig.Name, "factory_config_commission", key...)
	if err != nil {
		return "", err
	}
	return tableName, nil
}

// Insert inserts the FactoryConfigCommission to the database.
func (fcc *FactoryConfigCommission) Insert(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB
	var res sql.Result
	// if already exist, bail
	if fcc._exists {
		return errors.New("insert failed: already exists")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return err
	}

	// sql insert query, primary key provided by autoincrement
	sqlstr := `INSERT INTO ` + tableName +
		` (` +
		`fid, gcid, gid, plus_percent, abs_plus_price, created_at, updated_at, brand_id` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID)))
	if err != nil {
		return err
	}
	if tx != nil {
		res, err = tx.Exec(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID)
	} else {
		res, err = dbConn.Exec(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID)
	}

	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	fcc.ID = uint64(id)
	fcc._exists = true

	return nil
}

// Update updates the FactoryConfigCommission in the database.
func (fcc *FactoryConfigCommission) Update(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if fcc._deleted {
		return errors.New("update failed: marked for deletion")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return err
	}

	// sql query
	sqlstr := `UPDATE ` + tableName + ` SET ` +
		`fid = ?, gcid = ?, gid = ?, plus_percent = ?, abs_plus_price = ?, created_at = ?, updated_at = ?, brand_id = ?` +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID, fcc.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID, fcc.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, fcc.Fid, fcc.Gcid, fcc.Gid, fcc.PlusPercent, fcc.AbsPlusPrice, fcc.CreatedAt, fcc.UpdatedAt, fcc.BrandID, fcc.ID)
	}
	return err
}

// Save saves the FactoryConfigCommission to the database.
func (fcc *FactoryConfigCommission) Save(ctx context.Context) error {
	if fcc.Exists() {
		return fcc.Update(ctx)
	}

	return fcc.Insert(ctx)
}

// Delete deletes the FactoryConfigCommission from the database.
func (fcc *FactoryConfigCommission) Delete(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if fcc._deleted {
		return nil
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return err
	}
	//1

	// sql query with composite primary key
	sqlstr := `UPDATE ` + tableName + ` SET is_del = 1 WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fcc.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, fcc.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, fcc.ID)
	}

	if err != nil {
		return err
	}

	// set deleted
	fcc._deleted = true

	return nil
}

// FactoryConfigCommissionsByFid retrieves a row from 'aypcddg.factory_config_commission' as a FactoryConfigCommission.
//
// Generated from index 'factory_config_commission_fid_index'.
func FactoryConfigCommissionsByFid(ctx context.Context, fid int, key ...interface{}) ([]*FactoryConfigCommission, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, gcid, gid, plus_percent, abs_plus_price, created_at, updated_at, brand_id ` +
		`FROM ` + tableName +
		` WHERE fid = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fid)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	var queryData *sql.Rows
	if tx != nil {
		queryData, err = tx.Query(sqlstr, fid)
		if err != nil {
			return nil, err
		}
	} else {
		queryData, err = dbConn.Query(sqlstr, fid)
		if err != nil {
			return nil, err
		}
	}

	defer queryData.Close()

	// load results
	res := make([]*FactoryConfigCommission, 0)
	for queryData.Next() {
		fcc := FactoryConfigCommission{
			_exists: true,
		}

		// scan
		err = queryData.Scan(&fcc.ID, &fcc.Fid, &fcc.Gcid, &fcc.Gid, &fcc.PlusPercent, &fcc.AbsPlusPrice, &fcc.CreatedAt, &fcc.UpdatedAt, &fcc.BrandID)
		if err != nil {
			return nil, err
		}

		res = append(res, &fcc)
	}

	return res, nil
}

// FactoryConfigCommissionsByGcid retrieves a row from 'aypcddg.factory_config_commission' as a FactoryConfigCommission.
//
// Generated from index 'factory_config_commission_gcid_index'.
func FactoryConfigCommissionsByGcid(ctx context.Context, gcid int, key ...interface{}) ([]*FactoryConfigCommission, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, gcid, gid, plus_percent, abs_plus_price, created_at, updated_at, brand_id ` +
		`FROM ` + tableName +
		` WHERE gcid = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, gcid)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	var queryData *sql.Rows
	if tx != nil {
		queryData, err = tx.Query(sqlstr, gcid)
		if err != nil {
			return nil, err
		}
	} else {
		queryData, err = dbConn.Query(sqlstr, gcid)
		if err != nil {
			return nil, err
		}
	}

	defer queryData.Close()

	// load results
	res := make([]*FactoryConfigCommission, 0)
	for queryData.Next() {
		fcc := FactoryConfigCommission{
			_exists: true,
		}

		// scan
		err = queryData.Scan(&fcc.ID, &fcc.Fid, &fcc.Gcid, &fcc.Gid, &fcc.PlusPercent, &fcc.AbsPlusPrice, &fcc.CreatedAt, &fcc.UpdatedAt, &fcc.BrandID)
		if err != nil {
			return nil, err
		}

		res = append(res, &fcc)
	}

	return res, nil
}

// FactoryConfigCommissionsByGid retrieves a row from 'aypcddg.factory_config_commission' as a FactoryConfigCommission.
//
// Generated from index 'factory_config_commission_gid_index'.
func FactoryConfigCommissionsByGid(ctx context.Context, gid int, key ...interface{}) ([]*FactoryConfigCommission, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, gcid, gid, plus_percent, abs_plus_price, created_at, updated_at, brand_id ` +
		`FROM ` + tableName +
		` WHERE gid = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, gid)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	var queryData *sql.Rows
	if tx != nil {
		queryData, err = tx.Query(sqlstr, gid)
		if err != nil {
			return nil, err
		}
	} else {
		queryData, err = dbConn.Query(sqlstr, gid)
		if err != nil {
			return nil, err
		}
	}

	defer queryData.Close()

	// load results
	res := make([]*FactoryConfigCommission, 0)
	for queryData.Next() {
		fcc := FactoryConfigCommission{
			_exists: true,
		}

		// scan
		err = queryData.Scan(&fcc.ID, &fcc.Fid, &fcc.Gcid, &fcc.Gid, &fcc.PlusPercent, &fcc.AbsPlusPrice, &fcc.CreatedAt, &fcc.UpdatedAt, &fcc.BrandID)
		if err != nil {
			return nil, err
		}

		res = append(res, &fcc)
	}

	return res, nil
}

// FactoryConfigCommissionByID retrieves a row from 'aypcddg.factory_config_commission' as a FactoryConfigCommission.
//
// Generated from index 'factory_config_commission_id_pkey'.
func FactoryConfigCommissionByID(ctx context.Context, id uint64, key ...interface{}) (*FactoryConfigCommission, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFactoryConfigCommissionTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, fid, gcid, gid, plus_percent, abs_plus_price, created_at, updated_at, brand_id ` +
		`FROM ` + tableName +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, id)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	fcc := FactoryConfigCommission{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, id).Scan(&fcc.ID, &fcc.Fid, &fcc.Gcid, &fcc.Gid, &fcc.PlusPercent, &fcc.AbsPlusPrice, &fcc.CreatedAt, &fcc.UpdatedAt, &fcc.BrandID)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, id).Scan(&fcc.ID, &fcc.Fid, &fcc.Gcid, &fcc.Gid, &fcc.PlusPercent, &fcc.AbsPlusPrice, &fcc.CreatedAt, &fcc.UpdatedAt, &fcc.BrandID)
		if err != nil {
			return nil, err
		}
	}

	return &fcc, nil
}
