// Package xo contains the types for schema 'ddg_local'.
package xo

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"j7go/components"
	"j7go/utils"
	"time"

	"go.uber.org/zap"
)

// FlywaySchemaHistory represents a row from 'ddg_local.flyway_schema_history'.
type FlywaySchemaHistory struct {
	InstalledRank int            `json:"installed_rank"` // installed_rank
	Version       sql.NullString `json:"version"`        // version
	Description   string         `json:"description"`    // description
	Type          string         `json:"type"`           // type
	Script        string         `json:"script"`         // script
	Checksum      sql.NullInt64  `json:"checksum"`       // checksum
	InstalledBy   string         `json:"installed_by"`   // installed_by
	InstalledOn   time.Time      `json:"installed_on"`   // installed_on
	ExecutionTime int            `json:"execution_time"` // execution_time
	Success       bool           `json:"success"`        // success

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the FlywaySchemaHistory exists in the database.
func (fsh *FlywaySchemaHistory) Exists() bool { //flyway_schema_history
	return fsh._exists
}

// Deleted provides information if the FlywaySchemaHistory has been deleted from the database.
func (fsh *FlywaySchemaHistory) Deleted() bool {
	return fsh._deleted
}

// Get table name
func GetFlywaySchemaHistoryTableName(key ...interface{}) (string, error) {
	tableName, err := components.M.GetTable("ddg_local", "flyway_schema_history", key...)
	if err != nil {
		return "", err
	}
	return tableName, nil
}

// Insert inserts the FlywaySchemaHistory to the database.
func (fsh *FlywaySchemaHistory) Insert(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB
	var res sql.Result
	// if already exist, bail
	if fsh._exists {
		return errors.New("insert failed: already exists")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFlywaySchemaHistoryTableName(key...)
	if err != nil {
		return err
	}

	// sql insert query, primary key must be provided
	sqlstr := `INSERT INTO ` + tableName +
		` (` +
		`installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fsh.InstalledRank, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success)))
	if tx != nil {
		res, err = tx.Exec(sqlstr, fsh.InstalledRank, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success)
	} else {
		res, err = dbConn.Exec(sqlstr, fsh.InstalledRank, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success)
	}

	if err != nil {
		return err
	}

	// set existence
	fsh._exists = true

	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	fsh.InstalledRank = int(id)
	fsh._exists = true

	return nil
}

// Update updates the FlywaySchemaHistory in the database.
func (fsh *FlywaySchemaHistory) Update(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if fsh._deleted {
		return errors.New("update failed: marked for deletion")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFlywaySchemaHistoryTableName(key...)
	if err != nil {
		return err
	}

	// sql query
	sqlstr := `UPDATE ` + tableName + ` SET ` +
		`version = ?, description = ?, type = ?, script = ?, checksum = ?, installed_by = ?, installed_on = ?, execution_time = ?, success = ?` +
		` WHERE installed_rank = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success, fsh.InstalledRank)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success, fsh.InstalledRank)
	} else {
		_, err = dbConn.Exec(sqlstr, fsh.Version, fsh.Description, fsh.Type, fsh.Script, fsh.Checksum, fsh.InstalledBy, fsh.InstalledOn, fsh.ExecutionTime, fsh.Success, fsh.InstalledRank)
	}
	return err
}

// Save saves the FlywaySchemaHistory to the database.
func (fsh *FlywaySchemaHistory) Save(ctx context.Context) error {
	if fsh.Exists() {
		return fsh.Update(ctx)
	}

	return fsh.Insert(ctx)
}

// Delete deletes the FlywaySchemaHistory from the database.
func (fsh *FlywaySchemaHistory) Delete(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if fsh._deleted {
		return nil
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetFlywaySchemaHistoryTableName(key...)
	if err != nil {
		return err
	}
	//1

	// sql query with composite primary key
	sqlstr := `UPDATE ` + tableName + ` SET is_del = 1 WHERE installed_rank = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, fsh.InstalledRank)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, fsh.InstalledRank)
	} else {
		_, err = dbConn.Exec(sqlstr, fsh.InstalledRank)
	}

	if err != nil {
		return err
	}

	// set deleted
	fsh._deleted = true

	return nil
}

// FlywaySchemaHistoryByInstalledRank retrieves a row from 'ddg_local.flyway_schema_history' as a FlywaySchemaHistory.
//
// Generated from index 'flyway_schema_history_installed_rank_pkey'.
func FlywaySchemaHistoryByInstalledRank(ctx context.Context, installedRank int, key ...interface{}) (*FlywaySchemaHistory, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFlywaySchemaHistoryTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success ` +
		`FROM ` + tableName +
		` WHERE installed_rank = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, installedRank)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	fsh := FlywaySchemaHistory{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, installedRank).Scan(&fsh.InstalledRank, &fsh.Version, &fsh.Description, &fsh.Type, &fsh.Script, &fsh.Checksum, &fsh.InstalledBy, &fsh.InstalledOn, &fsh.ExecutionTime, &fsh.Success)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, installedRank).Scan(&fsh.InstalledRank, &fsh.Version, &fsh.Description, &fsh.Type, &fsh.Script, &fsh.Checksum, &fsh.InstalledBy, &fsh.InstalledOn, &fsh.ExecutionTime, &fsh.Success)
		if err != nil {
			return nil, err
		}
	}

	return &fsh, nil
}

// FlywaySchemaHistoriesBySuccess retrieves a row from 'ddg_local.flyway_schema_history' as a FlywaySchemaHistory.
//
// Generated from index 'flyway_schema_history_s_idx'.
func FlywaySchemaHistoriesBySuccess(ctx context.Context, success bool, key ...interface{}) ([]*FlywaySchemaHistory, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetFlywaySchemaHistoryTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success ` +
		`FROM ` + tableName +
		` WHERE success = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, success)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	var queryData *sql.Rows
	if tx != nil {
		queryData, err = tx.Query(sqlstr, success)
		if err != nil {
			return nil, err
		}
	} else {
		queryData, err = dbConn.Query(sqlstr, success)
		if err != nil {
			return nil, err
		}
	}

	defer queryData.Close()

	// load results
	res := make([]*FlywaySchemaHistory, 0)
	for queryData.Next() {
		fsh := FlywaySchemaHistory{
			_exists: true,
		}

		// scan
		err = queryData.Scan(&fsh.InstalledRank, &fsh.Version, &fsh.Description, &fsh.Type, &fsh.Script, &fsh.Checksum, &fsh.InstalledBy, &fsh.InstalledOn, &fsh.ExecutionTime, &fsh.Success)
		if err != nil {
			return nil, err
		}

		res = append(res, &fsh)
	}

	return res, nil
}
