// Package xo contains the types for schema 'aypcddg'.
package xo

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"j7go/components"
	"j7go/utils"

	"go.uber.org/zap"
)

// J7Migration represents a row from 'aypcddg.j7_migrations'.
type J7Migration struct {
	ID        uint   `json:"id"`        // id
	Migration string `json:"migration"` // migration
	Batch     int    `json:"batch"`     // batch

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the J7Migration exists in the database.
func (j *J7Migration) Exists() bool { //j7_migrations
	return j._exists
}

// Deleted provides information if the J7Migration has been deleted from the database.
func (j *J7Migration) Deleted() bool {
	return j._deleted
}

// Get table name
func GetJ7MigrationTableName(key ...interface{}) (string, error) {
	tableName, err := components.M.GetTable(components.E.Opts.DBConfig.Name, "j7_migrations", key...)
	if err != nil {
		return "", err
	}
	return tableName, nil
}

// Insert inserts the J7Migration to the database.
func (j *J7Migration) Insert(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB
	var res sql.Result
	// if already exist, bail
	if j._exists {
		return errors.New("insert failed: already exists")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetJ7MigrationTableName(key...)
	if err != nil {
		return err
	}

	// sql insert query, primary key provided by autoincrement
	sqlstr := `INSERT INTO ` + tableName +
		` (` +
		`migration, batch` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, j.Migration, j.Batch)))
	if err != nil {
		return err
	}
	if tx != nil {
		res, err = tx.Exec(sqlstr, j.Migration, j.Batch)
	} else {
		res, err = dbConn.Exec(sqlstr, j.Migration, j.Batch)
	}

	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	j.ID = uint(id)
	j._exists = true

	return nil
}

// Update updates the J7Migration in the database.
func (j *J7Migration) Update(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if j._deleted {
		return errors.New("update failed: marked for deletion")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetJ7MigrationTableName(key...)
	if err != nil {
		return err
	}

	// sql query
	sqlstr := `UPDATE ` + tableName + ` SET ` +
		`migration = ?, batch = ?` +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, j.Migration, j.Batch, j.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, j.Migration, j.Batch, j.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, j.Migration, j.Batch, j.ID)
	}
	return err
}

// Save saves the J7Migration to the database.
func (j *J7Migration) Save(ctx context.Context) error {
	if j.Exists() {
		return j.Update(ctx)
	}

	return j.Insert(ctx)
}

// Delete deletes the J7Migration from the database.
func (j *J7Migration) Delete(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if j._deleted {
		return nil
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetJ7MigrationTableName(key...)
	if err != nil {
		return err
	}
	//1

	// sql query with composite primary key
	sqlstr := `UPDATE ` + tableName + ` SET is_del = 1 WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, j.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, j.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, j.ID)
	}

	if err != nil {
		return err
	}

	// set deleted
	j._deleted = true

	return nil
}

// J7MigrationByID retrieves a row from 'aypcddg.j7_migrations' as a J7Migration.
//
// Generated from index 'j7_migrations_id_pkey'.
func J7MigrationByID(ctx context.Context, id uint, key ...interface{}) (*J7Migration, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetJ7MigrationTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, migration, batch ` +
		`FROM ` + tableName +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, id)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	j := J7Migration{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, id).Scan(&j.ID, &j.Migration, &j.Batch)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, id).Scan(&j.ID, &j.Migration, &j.Batch)
		if err != nil {
			return nil, err
		}
	}

	return &j, nil
}

// J7MigrationByMigration retrieves a row from 'aypcddg.j7_migrations' as a J7Migration.
//
// Generated from index 'migration'.
func J7MigrationByMigration(ctx context.Context, migration string, key ...interface{}) (*J7Migration, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetJ7MigrationTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, migration, batch ` +
		`FROM ` + tableName +
		` WHERE migration = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, migration)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	j := J7Migration{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, migration).Scan(&j.ID, &j.Migration, &j.Batch)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, migration).Scan(&j.ID, &j.Migration, &j.Batch)
		if err != nil {
			return nil, err
		}
	}

	return &j, nil
}
