// Package xo contains the types for schema 'ddg_local'.
package xo

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"j7go/components"
	"j7go/utils"

	"github.com/go-sql-driver/mysql"
	"go.uber.org/zap"
)

// PlatformWallet represents a row from 'ddg_local.platform_wallet'.
type PlatformWallet struct {
	ID           int64           `json:"id"`            // id
	ObtainMoney  sql.NullFloat64 `json:"obtain_money"`  // obtain_money
	ConsumeMoney sql.NullFloat64 `json:"consume_money"` // consume_money
	UseStatus    sql.NullInt64   `json:"use_status"`    // use_status
	CreatedAt    mysql.NullTime  `json:"created_at"`    // created_at
	UpdateAt     mysql.NullTime  `json:"update_at"`     // update_at
	Versions     sql.NullInt64   `json:"versions"`      // versions

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the PlatformWallet exists in the database.
func (pw *PlatformWallet) Exists() bool { //platform_wallet
	return pw._exists
}

// Deleted provides information if the PlatformWallet has been deleted from the database.
func (pw *PlatformWallet) Deleted() bool {
	return pw._deleted
}

// Get table name
func GetPlatformWalletTableName(key ...interface{}) (string, error) {
	tableName, err := components.M.GetTable("ddg_local", "platform_wallet", key...)
	if err != nil {
		return "", err
	}
	return tableName, nil
}

// Insert inserts the PlatformWallet to the database.
func (pw *PlatformWallet) Insert(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB
	var res sql.Result
	// if already exist, bail
	if pw._exists {
		return errors.New("insert failed: already exists")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetPlatformWalletTableName(key...)
	if err != nil {
		return err
	}

	// sql insert query, primary key provided by autoincrement
	sqlstr := `INSERT INTO ` + tableName +
		` (` +
		`obtain_money, consume_money, use_status, created_at, update_at, versions` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions)))
	if err != nil {
		return err
	}
	if tx != nil {
		res, err = tx.Exec(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions)
	} else {
		res, err = dbConn.Exec(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions)
	}

	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	pw.ID = int64(id)
	pw._exists = true

	return nil
}

// Update updates the PlatformWallet in the database.
func (pw *PlatformWallet) Update(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if pw._deleted {
		return errors.New("update failed: marked for deletion")
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetPlatformWalletTableName(key...)
	if err != nil {
		return err
	}

	// sql query
	sqlstr := `UPDATE ` + tableName + ` SET ` +
		`obtain_money = ?, consume_money = ?, use_status = ?, created_at = ?, update_at = ?, versions = ?` +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions, pw.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions, pw.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, pw.ObtainMoney, pw.ConsumeMoney, pw.UseStatus, pw.CreatedAt, pw.UpdateAt, pw.Versions, pw.ID)
	}
	return err
}

// Save saves the PlatformWallet to the database.
func (pw *PlatformWallet) Save(ctx context.Context) error {
	if pw.Exists() {
		return pw.Update(ctx)
	}

	return pw.Insert(ctx)
}

// Delete deletes the PlatformWallet from the database.
func (pw *PlatformWallet) Delete(ctx context.Context, key ...interface{}) error {
	var err error
	var dbConn *sql.DB

	// if deleted, bail
	if pw._deleted {
		return nil
	}

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetMasterConn()
		if err != nil {
			return err
		}
	}

	tableName, err := GetPlatformWalletTableName(key...)
	if err != nil {
		return err
	}
	//1

	// sql query with composite primary key
	sqlstr := `UPDATE ` + tableName + ` SET is_del = 1 WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, pw.ID)))
	if tx != nil {
		_, err = tx.Exec(sqlstr, pw.ID)
	} else {
		_, err = dbConn.Exec(sqlstr, pw.ID)
	}

	if err != nil {
		return err
	}

	// set deleted
	pw._deleted = true

	return nil
}

// PlatformWalletByID retrieves a row from 'ddg_local.platform_wallet' as a PlatformWallet.
//
// Generated from index 'platform_wallet_id_pkey'.
func PlatformWalletByID(ctx context.Context, id int64, key ...interface{}) (*PlatformWallet, error) {
	var err error
	var dbConn *sql.DB

	tableName, err := GetPlatformWalletTableName(key...)
	if err != nil {
		return nil, err
	}

	// sql query
	sqlstr := `SELECT ` +
		`id, obtain_money, consume_money, use_status, created_at, update_at, versions ` +
		`FROM ` + tableName +
		` WHERE id = ?`

	// run query
	utils.GetTraceLog(ctx).Debug("DB", zap.String("SQL", fmt.Sprint(sqlstr, id)))

	tx, err := components.M.GetConnFromCtx(ctx)
	if err != nil {
		dbConn, err = components.M.GetSlaveConn()
		if err != nil {
			return nil, err
		}
	}
	pw := PlatformWallet{
		_exists: true,
	}

	if tx != nil {
		err = tx.QueryRow(sqlstr, id).Scan(&pw.ID, &pw.ObtainMoney, &pw.ConsumeMoney, &pw.UseStatus, &pw.CreatedAt, &pw.UpdateAt, &pw.Versions)
		if err != nil {
			return nil, err
		}
	} else {
		err = dbConn.QueryRow(sqlstr, id).Scan(&pw.ID, &pw.ObtainMoney, &pw.ConsumeMoney, &pw.UseStatus, &pw.CreatedAt, &pw.UpdateAt, &pw.Versions)
		if err != nil {
			return nil, err
		}
	}

	return &pw, nil
}
